version: "3"

services:
  pb-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pb-web
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "${NEXT_PUBLIC_APP_PORT}:${NEXT_PUBLIC_APP_PORT}"
